### PR TITLE
fix: Update dependencies to resolve knex security vulnerabilities.

### LINKED ISSUE #26: [bug] fix CI errors
See: https://github.com/node-casbin/basic-adapter/actions/runs/5822029403/job/15786035155?pr=25

image

### PR DESCRIPTION
**Pull request by mslosarek**
This change updated the dependencies and brings the libraries up to date. 
Specifically, this change is to fix Knex: https://github.com/advisories/GHSA-4jv9-3563-23j3
It also includes a docker-compose.yml file that will spin up versions of the databases to test against.

Fix: https://github.com/node-casbin/basic-adapter/issues/26

### CODE REVIEW

**Comment by hsluoyz** [comment]
@mslosarek plz fix CI:

image

**Comment by hsluoyz** [comment]
@mslosarek fix linter CI

**Comment by mslosarek** [comment]
> @mslosarek fix linter CI

Sorry, made a change after the last fix and forgot to rerun the linting

**Comment by hsluoyz** [comment]
@mslosarek that's OK. BTW, does this PR also fix this issue: https://github.com/node-casbin/basic-adapter/issues/24 ?

**Comment by mslosarek** [comment]
Sort of. It suppresses the warning message from Knex. I am working on a separate story that perform the create if not exists without using that method. The Knex prescribed solution assumes that you are using Knex to perform your queries, which this library does not do.

**Pull request merged**
